replicaCount: 2
image:
  repository: registry.arc-center.run/silverkeytech/fileblogsystem/ba5ma
  pullPolicy: IfNotPresent
  tag: ba5ma-fileblogsystem-dev-latest

resources:
  requests:
    cpu: 60m
    memory: 60M
